on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 66Leo66-4T1M-Paper
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 18
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 66Leo66-4T1M-Paper
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 18
      - run: yarn build